bot_status: "Im workin"


notifications_channel: true


# do you want to use notes?
notes_channels: true
# do you want to use a task manager?
task_manager: true


# !reset command clears all the channels on the server that were used by a bot
reset_command: true
# !hard_reset command clears all the channels on the server
hard_reset_command: true